<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NSDeck.Core\NSDeck.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="PowerShell\WindowsDnsWorker.ps1"
                      LogicalName="NSDeck.WindowsDnsWorker.ps1" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>NSDeck.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
